version: '3.7'
services:
  app:
    build:
      context: ./app
      args:
        ENVIRONMENT: development
    ports:
      - "80:3000" # Map the container's port to port 80 on the host
    links:
      - cms
    environment:
      CLIENT_API_HOST: http://localhost:4000
      SERVER_API_HOST: cms:4000
    volumes:
      - ./app:/src

  cms:
    build:
      context: ./cms
    ports:
      - "4000:4000"
    volumes:
      - ./cms:/src
